steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${docker.project.namespace}/${docker.image.name}:${docker.tag.long}', 'tomcat/target/docker-src']

- name: 'gcr.io/gcp-runtimes/structure_test'
  args: [
    '--image',
    '${cloudbuild.tomcat.image}',
    '-v',
    '--config',
    '/workspace/tomcat/target/test-classes/structure.yaml']

images:
- '${cloudbuild.tomcat.image}'
